### PR TITLE
Use more generic example to demonstrate estimate()

### PR DESCRIPTION
**Pull request by stuartpb**

### CODE REVIEW

**Comment by annevk** [comment]
This looks reasonable. Any reason you wanted to change this?

**Comment by marcoscaceres** [comment]
I prefer the original, tbh. It's easier to reason about concrete things (like the game level). There is also less redundant code.

**Comment by stuartpb** [comment]
> This looks reasonable. Any reason you wanted to change this?

Well, it all started with Metroid being misspelled "Metriod" 😜 

Beyond that:

- Everything else in the document pretty much sticks to "just the facts" and this bizarre, needlessly-specific conjectural offshoot sticks out like a sore thumb
- Picking a specific example like this makes more general applications of this paradigm *harder* to derive, not easier
- Metroid is a registered trademark of Nintendo, with Metroid Prime being a specific work that has already been written, which any programmer reading would not legally be allowed to reimplement unless they were explicitly authorized by Nintendo
- Throwing an error when there's not enough room to cache the next area in a game doesn't make sense (are we just going to make the player explode when they try to go there?)

Even just as an abstract base, Metroid Prime is bad as a *specific* example, as Metroid Prime's map loading was famously built in to its level design, [with every room being just large enough to hide the load times all the rooms accessible from its neighbors, based on the expected load times of the hardware being shorter than the time needed to move through the room](https://www.reddit.com/r/truegaming/comments/1ebkcw/metroid_prime_enginelevel_design/c9yuphk). This leads to a lot of guarantees being necessary for the game to operate smoothly, and the existing hypothetical example scenario runs *directly counter* to what those guarantees would need to be.

**Comment by annevk** [comment]
Thanks so much, best justification ever! 😊

**Comment by marcoscaceres** [comment]
I concur! Hats off.

**Pull request merged**
