### PR TITLE
Support obtaining a StorageKey from an environment. (Fixes #137)

### LINKED ISSUE #137: "obtain a storage key" needs to operate on an environment
Currently the "obtain a storage key" algorithm operates on an environment settings object.  For service workers, however, we need to obtain a storage key from a service worker client that may just be an environment.  For example, to obtain the service worker for a client before the navigation request completes and the environment is not loaded yet.

I'd like to change these algorithms to take environment instead of environment settings object.  The origin would be extracted from the creation URL.

@annevk WDYT?

### PR DESCRIPTION
**Pull request by wanderview**
***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 3, 2022, 2:00 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwanderview%2Fstorage%2F143ae6927d9d5760e0b7e6416ed39f1d89f3a7b1%2Fstorage.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%20138)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20whatwg/storage%23138.)._
</details>

### CODE REVIEW

**Comment by wanderview** [comment]
@annevk PTAL.  Thanks.

**Review by annevk — COMMENTED** [review]
Looks good modulo formatting nits.

**Comment by wanderview** [comment]
Thanks.  Suggestions committed to the branch.

**Review by annevk — APPROVED** [review]

**Comment by annevk** [comment]
Sigh. I wanted to merge this but CI keeps returning server errors. Please remind me to get back to this?

**Pull request merged**
